/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainJFrame.java
 *
 * Created on 3.5.2010, 20:02:35
 */

package carrental.GUI;

import java.awt.Dimension;
import java.awt.TextArea;
import javax.swing.JLabel;

/**
 *
 * @author SirGlorg
 */
public class MainJFrame extends javax.swing.JFrame {

    /** Creates new form MainJFrame */
    public MainJFrame() {
        initComponents();
		TextArea ta = new TextArea(5,100);
		jScrollPane_Customers.add(ta);
		ta.setPreferredSize(new Dimension(100,100));
		ta.setText("I don't know... this is dum");
		//for (int i = 0; i < 20; i++) {
		//}
		jScrollPane_Customers.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_Main = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_find = new javax.swing.JLabel();
        jTextField_findCustomer = new javax.swing.JTextField();
        jButton_newCustomer = new javax.swing.JButton();
        jButton_findCustomer = new javax.swing.JButton();
        jScrollPane_Customers = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Settings = new javax.swing.JMenu();
        jMenu_Settings_Language = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jTabbedPane_Main.setName("jTabbedPane_Main"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(carrental.CarRentalApp.class).getContext().getResourceMap(MainJFrame.class);
        jLabel_find.setText(resourceMap.getString("jLabel_find.text")); // NOI18N
        jLabel_find.setName("jLabel_find"); // NOI18N

        jTextField_findCustomer.setText(resourceMap.getString("jTextField_findCustomer.text")); // NOI18N
        jTextField_findCustomer.setName("jTextField_findCustomer"); // NOI18N
        jTextField_findCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_findCustomerActionPerformed(evt);
            }
        });

        jButton_newCustomer.setText(resourceMap.getString("jButton_newCustomer.text")); // NOI18N
        jButton_newCustomer.setName("jButton_newCustomer"); // NOI18N

        jButton_findCustomer.setText(resourceMap.getString("jButton_findCustomer.text")); // NOI18N
        jButton_findCustomer.setName("jButton_findCustomer"); // NOI18N

        jScrollPane_Customers.setName("jScrollPane_Customers"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_Customers, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_find)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_findCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_findCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_newCustomer)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_find)
                    .addComponent(jTextField_findCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_findCustomer)
                    .addComponent(jButton_newCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Customers, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jTabbedPane_Main.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu_Settings.setText(resourceMap.getString("jMenu_Settings.text")); // NOI18N
        jMenu_Settings.setName("jMenu_Settings"); // NOI18N

        jMenu_Settings_Language.setText(resourceMap.getString("jMenu_Settings_Language.text")); // NOI18N
        jMenu_Settings_Language.setName("jMenu_Settings_Language"); // NOI18N
        jMenu_Settings_Language.setPreferredSize(new java.awt.Dimension(100, 22));
        jMenu_Settings.add(jMenu_Settings_Language);

        jMenuBar1.add(jMenu_Settings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jTextField_findCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_findCustomerActionPerformed
		//TODO on_press should react to the <enter> keyboard key and trigger finding
	}//GEN-LAST:event_jTextField_findCustomerActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_findCustomer;
    private javax.swing.JButton jButton_newCustomer;
    private javax.swing.JLabel jLabel_find;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Settings;
    private javax.swing.JMenuItem jMenu_Settings_Language;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane_Customers;
    private javax.swing.JTabbedPane jTabbedPane_Main;
    private javax.swing.JTextField jTextField_findCustomer;
    // End of variables declaration//GEN-END:variables

}
