/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCustomerDialog.java
 *
 * Created on 12.5.2010, 14:17:04
 */

package carrental;

import carrental.models.CustomerStateModel;
import carrental.entities.Address;
import carrental.entities.Customer;
import carrental.managers.CustomerManagerException;
import carrental.managers.CustomerManagerImpl;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SirGlorg
 */
public class AddCustomerDialog extends javax.swing.JDialog {

	private Customer resultCustomer;

    /** Creates new form AddCustomerDialog */
    public AddCustomerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
		CustomerStateModel acm = (CustomerStateModel) jComboBoxState.getModel();
		acm.addCountries();
		resultCustomer = null;
    }

	/**
	 * gets the newly generated <code>Customer</code>
	 * @return Customer the newly generated <code>Customer</code>
	 */
	public Customer getResultCustomer() {
		return resultCustomer;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelForename = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jTextFieldForename = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxState = new javax.swing.JComboBox();
        jTextFieldStreet = new javax.swing.JTextField();
        jTextFieldHousenumber = new javax.swing.JTextField();
        jTextFieldTown = new javax.swing.JTextField();
        jTextFieldZipcode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        jLabelForename.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("Forename") + ":");
        jLabelForename.setName("jLabelForename"); // NOI18N

        jLabelSurname.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("Surname") + ":");
        jLabelSurname.setName("jLabelSurname"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(carrental.CarRentalApp.class).getContext().getResourceMap(AddCustomerDialog.class);
        jTextFieldForename.setText(resourceMap.getString("jTextFieldForename.text")); // NOI18N
        jTextFieldForename.setName("jTextFieldForename"); // NOI18N
        jTextFieldForename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForenameActionPerformed(evt);
            }
        });

        jTextFieldSurname.setText(resourceMap.getString("jTextFieldSurname.text")); // NOI18N
        jTextFieldSurname.setName("jTextFieldSurname"); // NOI18N

        jLabel1.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("Address")+":");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("Street") + ":");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("HouseNumber") + ":");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("Town") + ":");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("State") + ":");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(java.util.ResourceBundle.getBundle("carrental/texts",this.getParent().getLocale()).getString("Zipcode") + ":");
        jLabel6.setName("jLabel6"); // NOI18N

        jComboBoxState.setModel(new carrental.models.CustomerStateModel());
        jComboBoxState.setName("jComboBoxState"); // NOI18N

        jTextFieldStreet.setText(resourceMap.getString("jTextFieldStreet.text")); // NOI18N
        jTextFieldStreet.setName("jTextFieldStreet"); // NOI18N

        jTextFieldHousenumber.setText(resourceMap.getString("jTextFieldHousenumber.text")); // NOI18N
        jTextFieldHousenumber.setName("jTextFieldHousenumber"); // NOI18N

        jTextFieldTown.setText(resourceMap.getString("jTextFieldTown.text")); // NOI18N
        jTextFieldTown.setName("jTextFieldTown"); // NOI18N

        jTextFieldZipcode.setText(resourceMap.getString("jTextFieldZipcode.text")); // NOI18N
        jTextFieldZipcode.setName("jTextFieldZipcode"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
        jButtonAdd.setName("jButtonAdd"); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldZipcode, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxState, 0, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTown, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHousenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                        .addGap(13, 13, 13))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelForename)
                            .addComponent(jLabelSurname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextFieldForename, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelForename)
                    .addComponent(jTextFieldForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSurname)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldHousenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jTextFieldForenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForenameActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jTextFieldForenameActionPerformed

	private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
		int houseNumber = 0;
		try {
			houseNumber = Integer.parseInt(jTextFieldHousenumber.getText());
		} catch (NumberFormatException nfe) {
			JOptionPane.showMessageDialog(null, "House number is not a number!","Customer error",JOptionPane.ERROR_MESSAGE); //TODO locale
			return;
		}
		Object o = jComboBoxState.getSelectedItem();
		if (o == null) {
			JOptionPane.showMessageDialog(null, "Please select state.","Customer error",JOptionPane.ERROR_MESSAGE); //TODO locale
			return;
		}
		if (houseNumber > 0) {
			CustomerManagerImpl cmi = new CustomerManagerImpl();
			String forename = jTextFieldForename.getText();
			String surname = jTextFieldSurname.getText();
			String street = jTextFieldStreet.getText();
			String town = jTextFieldTown.getText();
			String state = jComboBoxState.getSelectedItem().toString();
			String zipcode = jTextFieldZipcode.getText();
			Address addr = new Address(1,houseNumber,street, town, state, zipcode); //address ID is not used in address creation, so it can be of any supporting value.
			try {
				resultCustomer = cmi.createNewCustomer(forename, surname, addr);
			} catch (CustomerManagerException ex) {
				Logger.getLogger(AddCustomerDialog.class.getName()).log(Level.SEVERE, null, ex);
				JOptionPane.showMessageDialog(null, "Customer insertion in the database failed!","Customer error",JOptionPane.ERROR_MESSAGE); //TODO locale
			}
			dispose();
		} else {
			JOptionPane.showMessageDialog(null, "House number should be greater than zero!","Customer error",JOptionPane.ERROR_MESSAGE); //TODO locale
		}
	}//GEN-LAST:event_jButtonAddActionPerformed

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		dispose();
	}//GEN-LAST:event_jButtonCancelActionPerformed

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelForename;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldForename;
    private javax.swing.JTextField jTextFieldHousenumber;
    private javax.swing.JTextField jTextFieldStreet;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldTown;
    private javax.swing.JTextField jTextFieldZipcode;
    // End of variables declaration//GEN-END:variables
	// </editor-fold>
}
