/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CarRentalFrame.java
 *
 * Created on 28.4.2010, 18:32:01
 */
package carrental;

import carrental.entities.Car;
import carrental.entities.CarType;
import carrental.entities.Customer;
import carrental.managers.CarManagerException;
import carrental.managers.CarManagerImpl;
import com.toedter.calendar.JCalendar;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.RowFilter.ComparisonType;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jerrycek
 */
public class CarRentalFrame extends javax.swing.JFrame {

	static Locale locale = new Locale("cs", "CZ");

	/** Creates new form CarRentalFrame */
	public CarRentalFrame() {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
		}
		initComponents();
		//jTextField1.setText("Find a customer");
		CarsTableModel cars = (CarsTableModel) jTableCars.getModel();
		cars.loadCars();
		CustomersTableModel customers = (CustomersTableModel) jTableCustomers.getModel();
		customers.loadCustomers();
		OrdersTableModel orders = (OrdersTableModel) jTableOrders.getModel();
		orders.loadOrders();
	}


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCustomers = new javax.swing.JPanel();
        jTextFieldFindCustomer = new javax.swing.JTextField();
        jLabelCustomersFind = new javax.swing.JLabel();
        jButtonCustomerFind = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomers = new javax.swing.JTable();
        jButtonCustomerAdd = new javax.swing.JButton();
        jButtonCustomerEdit = new javax.swing.JButton();
        jButtonCustomerDelete = new javax.swing.JButton();
        jPanelCars = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCars = new javax.swing.JTable();
        jButtonCarAdd = new javax.swing.JButton();
        jButtonCarEdit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelOrders = new javax.swing.JPanel();
        jTextFieldOrdersFind = new javax.swing.JTextField();
        jLabelOrdersFind = new javax.swing.JLabel();
        jButtonOrderFind = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrders = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanelTopMenu = new javax.swing.JPanel();
        jLabelCustomersLanguage = new javax.swing.JLabel();
        jButtonCustomersCzech = new javax.swing.JButton();
        jButtonCustomersSlovak = new javax.swing.JButton();
        jButtonCustomersEnglish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanelCustomers.setName("jPanelCustomers"); // NOI18N

        jTextFieldFindCustomer.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find a customer"));
        jTextFieldFindCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldFindCustomer.setName("jTextFieldFindCustomer"); // NOI18N
        jTextFieldFindCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFindCustomerMouseClicked(evt);
            }
        });
        jTextFieldFindCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFindCustomerKeyReleased(evt);
            }
        });

        jLabelCustomersFind.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find"));
        jLabelCustomersFind.setName("jLabelCustomersFind"); // NOI18N

        jButtonCustomerFind.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find"));
        jButtonCustomerFind.setName("jButtonCustomerFind"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        CustomersTableModel ctm = new CustomersTableModel();
        TableRowSorter sorter = new TableRowSorter(ctm);
        //sorter.setRowFilter(RowFilter.regexFilter(jTextFieldFindCustomer.getText()));
        //System.out.println(jTextFieldFindCustomer.getText());
        jTableCustomers.setModel(ctm);
        jTableCustomers.setName("jTableCustomers"); // NOI18N
        jTableCustomers.setRowSorter(sorter);
        jTableCustomers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableCustomers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCustomers);

        jButtonCustomerAdd.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Add"));
        jButtonCustomerAdd.setName("jButtonCustomerAdd"); // NOI18N
        jButtonCustomerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerAddActionPerformed(evt);
            }
        });

        jButtonCustomerEdit.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Edit"));
        jButtonCustomerEdit.setName("jButtonCustomerEdit"); // NOI18N
        jButtonCustomerEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerEditActionPerformed(evt);
            }
        });

        jButtonCustomerDelete.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Delete"));
        jButtonCustomerDelete.setName("jButtonCustomerDelete"); // NOI18N
        jButtonCustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustomersLayout = new javax.swing.GroupLayout(jPanelCustomers);
        jPanelCustomers.setLayout(jPanelCustomersLayout);
        jPanelCustomersLayout.setHorizontalGroup(
            jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustomersLayout.createSequentialGroup()
                        .addComponent(jLabelCustomersFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFindCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCustomerFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jButtonCustomerAdd)
                        .addGap(226, 226, 226))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomersLayout.createSequentialGroup()
                        .addComponent(jButtonCustomerDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCustomerEdit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCustomersLayout.setVerticalGroup(
            jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFindCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerFind)
                    .addComponent(jLabelCustomersFind)
                    .addComponent(jButtonCustomerAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCustomerEdit)
                    .addComponent(jButtonCustomerDelete))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Customers"), jPanelCustomers);

        jPanelCars.setName("jPanelCars"); // NOI18N

        jTextField2.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find a car"));
        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel2.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find"));
        jLabel2.setName("jLabel2"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        CarsTableModel cartm = new CarsTableModel();
        TableRowSorter carsorter = new TableRowSorter(cartm);
        jTableCars.setModel(cartm);
        jTableCars.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCars.setName("jTableCars"); // NOI18N
        jTableCars.setRowSorter(carsorter);
        jScrollPane2.setViewportView(jTableCars);

        jButtonCarAdd.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Add a car"));
        jButtonCarAdd.setName("jButtonCarAdd"); // NOI18N
        jButtonCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarAddActionPerformed(evt);
            }
        });

        jButtonCarEdit.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Edit car"));
        jButtonCarEdit.setName("jButtonCarEdit"); // NOI18N
        jButtonCarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarEditActionPerformed(evt);
            }
        });

        jButton1.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Delete car"));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCarsLayout = new javax.swing.GroupLayout(jPanelCars);
        jPanelCars.setLayout(jPanelCarsLayout);
        jPanelCarsLayout.setHorizontalGroup(
            jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCarsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(jButtonCarAdd)
                        .addGap(243, 243, 243))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarsLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCarEdit)))
                .addContainerGap())
        );
        jPanelCarsLayout.setVerticalGroup(
            jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonCarAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCarEdit)
                    .addComponent(jButton1))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Cars"), jPanelCars);

        jPanelOrders.setName("jPanelOrders"); // NOI18N

        jTextFieldOrdersFind.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find an order"));
        jTextFieldOrdersFind.setName("jTextFieldOrdersFind"); // NOI18N

        jLabelOrdersFind.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("FindLabel"));
        jLabelOrdersFind.setName("jLabelOrdersFind"); // NOI18N

        jButtonOrderFind.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find"));
        jButtonOrderFind.setName("jButtonOrderFind"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        OrdersTableModel ordertm = new OrdersTableModel();
        TableRowSorter orderSorter = new TableRowSorter(ordertm);
        jTableOrders.setModel(ordertm);
        jTableOrders.setName("jTableOrders"); // NOI18N
        jTableOrders.setRowSorter(orderSorter);
        jScrollPane3.setViewportView(jTableOrders);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(carrental.CarRentalApp.class).getContext().getResourceMap(CarRentalFrame.class);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setRolloverEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jButton5.setIcon(resourceMap.getIcon("jButton5.icon")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.setRolloverEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jSeparator4.setName("jSeparator4"); // NOI18N

        jTextField4.setEditable(false);
        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelOrdersLayout = new javax.swing.GroupLayout(jPanelOrders);
        jPanelOrders.setLayout(jPanelOrdersLayout);
        jPanelOrdersLayout.setHorizontalGroup(
            jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(jPanelOrdersLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOrdersLayout.createSequentialGroup()
                        .addComponent(jLabelOrdersFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldOrdersFind, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrderFind)))
                .addContainerGap())
        );
        jPanelOrdersLayout.setVerticalGroup(
            jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrdersFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOrderFind)
                    .addComponent(jLabelOrdersFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Orders"), jPanelOrders);

        jPanelTopMenu.setName("jPanelTopMenu"); // NOI18N

        jLabelCustomersLanguage.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Language"));
        jLabelCustomersLanguage.setName("jLabelCustomersLanguage"); // NOI18N

        jButtonCustomersCzech.setIcon(resourceMap.getIcon("jButtonCustomersCzech.icon")); // NOI18N
        jButtonCustomersCzech.setText(resourceMap.getString("jButtonCustomersCzech.text")); // NOI18N
        jButtonCustomersCzech.setName("jButtonCustomersCzech"); // NOI18N
        jButtonCustomersCzech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomersCzechActionPerformed(evt);
            }
        });

        jButtonCustomersSlovak.setIcon(resourceMap.getIcon("jButtonCustomersSlovak.icon")); // NOI18N
        jButtonCustomersSlovak.setName("jButtonCustomersSlovak"); // NOI18N
        jButtonCustomersSlovak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomersSlovakActionPerformed(evt);
            }
        });

        jButtonCustomersEnglish.setIcon(resourceMap.getIcon("jButtonCustomersEnglish.icon")); // NOI18N
        jButtonCustomersEnglish.setName("jButtonCustomersEnglish"); // NOI18N
        jButtonCustomersEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomersEnglishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopMenuLayout = new javax.swing.GroupLayout(jPanelTopMenu);
        jPanelTopMenu.setLayout(jPanelTopMenuLayout);
        jPanelTopMenuLayout.setHorizontalGroup(
            jPanelTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopMenuLayout.createSequentialGroup()
                .addContainerGap(630, Short.MAX_VALUE)
                .addComponent(jLabelCustomersLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCustomersCzech, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCustomersSlovak, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCustomersEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTopMenuLayout.setVerticalGroup(
            jPanelTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelCustomersLanguage)
                    .addComponent(jButtonCustomersCzech, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomersSlovak, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomersEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName(resourceMap.getString("jTabbedPane1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
		if (!jTextField5.getText().equals("")) {
			TableRowSorter sort = (TableRowSorter) jTableOrders.getRowSorter();
			jTextField5.setText("");
			sort.setRowFilter(null);
		}
}//GEN-LAST:event_jTextField5MouseClicked

	private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
		if (!jTextField4.getText().equals("")) {
			TableRowSorter sort = (TableRowSorter) jTableOrders.getRowSorter();
			jTextField4.setText("");
			sort.setRowFilter(null);
		}
}//GEN-LAST:event_jTextField4MouseClicked

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		final JCalendar cal = new JCalendar();
		DateFormat datf = DateFormat.getDateInstance(DateFormat.SHORT);
		Date dat = null;
		try {
			dat = datf.parse(jTextField5.getText());
		} catch (ParseException ex) {
			//Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
		}
		if (dat != null) {
			cal.setDate(dat);
		}
		final JFrame frame = new JFrame("JCALENDAR");
		frame.getContentPane().setLayout(new FlowLayout());
		frame.getContentPane().add(cal);
		JButton helloButton = new JButton();
		helloButton.setText("OK");
		frame.add(helloButton);
		frame.pack();
		MouseListener mouse = new MouseListener() {

			public void mouseClicked(MouseEvent e) {
				DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT);
				jTextField5.setText(df.format(cal.getDate()).toString());
				Date date = null;
				try {
					date = df.parse(jTextField5.getText());
					//System.out.println(date);
				} catch (ParseException ex) {
					Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
				}
				TableRowSorter sort = (TableRowSorter) jTableOrders.getRowSorter();
				if (date == null) {
					sort.setRowFilter(null);
				} else {
					sort.setRowFilter(RowFilter.dateFilter(ComparisonType.BEFORE, date));
				}
				frame.dispose();
			}

			public void mousePressed(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void mouseReleased(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void mouseEntered(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void mouseExited(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}
		};
		helloButton.addMouseListener(mouse);
		//cal.addMouseListener(mouse);
		frame.setVisible(true);
}//GEN-LAST:event_jButton5ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		final JCalendar cal = new JCalendar();
		DateFormat datf = DateFormat.getDateInstance(DateFormat.SHORT);
		Date dat = null;
		try {
			dat = datf.parse(jTextField4.getText());
		} catch (ParseException ex) {
			Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
		}
		if (dat != null) {
			cal.setDate(dat);
		}
		final JFrame frame = new JFrame("JCALENDAR");
		frame.getContentPane().setLayout(new FlowLayout());
		frame.getContentPane().add(cal);
		JButton helloButton = new JButton();
		helloButton.setText("OK");
		frame.add(helloButton);
		frame.pack();
		MouseListener mouse = new MouseListener() {

			public void mouseClicked(MouseEvent e) {
				DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT);
				jTextField4.setText(df.format(cal.getDate()).toString());
				Date date = null;
				try {
					date = df.parse(jTextField4.getText());
					//System.out.println(date);
				} catch (ParseException ex) {
					Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
				}
				TableRowSorter sort = (TableRowSorter) jTableOrders.getRowSorter();
				if (date == null) {
					sort.setRowFilter(null);
				} else {
					sort.setRowFilter(RowFilter.dateFilter(ComparisonType.AFTER, date));
				}
				frame.dispose();
			}

			public void mousePressed(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void mouseReleased(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void mouseEntered(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void mouseExited(MouseEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}
		};
		helloButton.addMouseListener(mouse);
		//cal.addMouseListener(mouse);
		frame.setVisible(true);
}//GEN-LAST:event_jButton4ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		if (jTableCars.getSelectedRow() != -1) {
			int i = JOptionPane.showConfirmDialog(rootPane, java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Do_you_really"));
			if (i == 0) {
				CarsTableModel cars = (CarsTableModel) jTableCars.getModel();
				Car car = cars.getCarAt(jTableCars.getSelectedRow());
				cars.deleteCar(car);
			}
		}
}//GEN-LAST:event_jButton1ActionPerformed

	private void jButtonCarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarEditActionPerformed
		if (jTableCars.getSelectedRow() != -1) {
			final JDialog dial = new EditCarDialog(this, rootPaneCheckingEnabled);
			final Component[] comp = dial.getContentPane().getComponents();
			CarsTableModel cars = (CarsTableModel) jTableCars.getModel();
			final Car car = cars.getCarAt(jTableCars.getSelectedRow());
			JTextField cname = (JTextField) comp[1];
			cname.setText(car.getName());
			JTextField cplate = (JTextField) comp[3];
			cplate.setText(car.getLicencePlate());
			JComboBox cstate = (JComboBox) comp[5];
			cstate.setSelectedItem(car.getState());
			//JComboBox ctype = (JComboBox) comp[7];
			//ctype.setSelectedItem(car.getCarType());
			JTextField ctype = (JTextField) comp[7];
			ctype.setText(car.getCarType().name());
			dial.setLocation(300, 100);
			dial.setVisible(true);
			WindowListener pcl = new WindowListener() {

				public void windowOpened(WindowEvent e) {
					//throw new UnsupportedOperationException("Not supported yet.");
				}

				public void windowClosing(WindowEvent e) {
					//throw new UnsupportedOperationException("Not supported yet.");
				}

				public void windowClosed(WindowEvent e) {
					JLabel c = (JLabel) comp[9];
					if (c.getText().equals(" ")) {
						Component[] comp = dial.getContentPane().getComponents();
						JTextField cname = (JTextField) comp[1];
						String name = cname.getText();
						JComboBox cstate = (JComboBox) comp[5];
						String state = cstate.getSelectedItem().toString();
						car.setName(name);
						car.setState(state);
						final CarsTableModel model = (CarsTableModel) jTableCars.getModel();
						model.editCar(car);
					}
				}

				public void windowIconified(WindowEvent e) {
					//throw new UnsupportedOperationException("Not supported yet.");
				}

				public void windowDeiconified(WindowEvent e) {
					//throw new UnsupportedOperationException("Not supported yet.");
				}

				public void windowActivated(WindowEvent e) {
					//throw new UnsupportedOperationException("Not supported yet.");
				}

				public void windowDeactivated(WindowEvent e) {
					//throw new UnsupportedOperationException("Not supported yet.");
				}
			};
			dial.addWindowListener(pcl);
		}
}//GEN-LAST:event_jButtonCarEditActionPerformed

	private void jButtonCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarAddActionPerformed
		final JDialog dial = new AddCarDialog(this, rootPaneCheckingEnabled);
		dial.setLocation(300, 100);
		dial.setVisible(true);
		WindowListener pcl = new WindowListener() {

			public void windowOpened(WindowEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void windowClosing(WindowEvent e) {
				//System.out.println("ahoj");
			}

			public void windowClosed(WindowEvent e) {
				Component[] comp = dial.getContentPane().getComponents();
				JLabel c = (JLabel) comp[9];
				if (c.getText().equals(" ")) {
					JTextField cname = (JTextField) comp[1];
					String name = cname.getText();
					JTextField cplate = (JTextField) comp[3];
					String licencePlate = cplate.getText();
					JComboBox cstate = (JComboBox) comp[5];
					String state = cstate.getSelectedItem().toString();
					JComboBox ctype = (JComboBox) comp[7];
					CarType type = CarType.valueOf(ctype.getSelectedItem().toString());
					final CarsTableModel model = (CarsTableModel) jTableCars.getModel();
					CarManagerImpl cmi = new CarManagerImpl();
					Car car = null;
					try {
						car = cmi.createNewCar(name, licencePlate, state, type);
					} catch (CarManagerException ex) {
						//Logger.getLogger(CarRentalFrame.class.getName()).log(Level.SEVERE, null, ex);
						JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Duplicity"));
					}
					if (car != null) {
						model.addCar(car);
						model.fireTableDataChanged();
					}
				}
			}

			public void windowIconified(WindowEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void windowDeiconified(WindowEvent e) {
				//System.out.println("ahoj3");
			}

			public void windowActivated(WindowEvent e) {
				//throw new UnsupportedOperationException("Not supported yet.");
			}

			public void windowDeactivated(WindowEvent e) {
				//System.out.println("ahoj2");
			}
		};
		dial.addWindowListener(pcl);
}//GEN-LAST:event_jButtonCarAddActionPerformed

	private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
		String text = jTextField2.getText();
		TableRowSorter sort = (TableRowSorter) jTableCars.getRowSorter();
		if (text.length() == 0) {
			sort.setRowFilter(null);
		} else {
			String[] filter = text.split(" ");
			if (filter.length > 0) {
				String newText = filter[0];
				int length = filter.length;
				for (int i = 1; i < length; i++) {
					newText += "|" + filter[i];
				}
				sort.setRowFilter(RowFilter.regexFilter(newText));
			}
		}
}//GEN-LAST:event_jTextField2KeyReleased

	private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
		jTextField2.setText("");
}//GEN-LAST:event_jTextField2MouseClicked

	private void jButtonCustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerDeleteActionPerformed
		if (jTableCustomers.getSelectedRow() != -1) {
			int i = JOptionPane.showConfirmDialog(this, "Do you really want to delete this customer?"); //TODO localization
			if (i == 0) {
				CustomersTableModel customersTable = (CustomersTableModel) jTableCustomers.getModel();
				Customer customer = customersTable.getCustomer(jTableCustomers.getSelectedRow());
				customersTable.deleteCustomer(customer);
			}
		} else {
			JOptionPane.showMessageDialog(this, "No customer is selected!","Customer error", JOptionPane.ERROR_MESSAGE); //TODO localization
		}
}//GEN-LAST:event_jButtonCustomerDeleteActionPerformed

	private void jButtonCustomerEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerEditActionPerformed
		//dialog building phase
		int selectedRow = jTableCustomers.getSelectedRow();
		if (selectedRow >= 0) {
			Customer customerToEdit = ((CustomersTableModel)jTableCustomers.getModel()).getCustomer(selectedRow);
			Customer customerToDialog = new Customer(customerToEdit); // gets a new instance of a different customer (hopefully)
			final JDialog dial = new EditCustomerDialog(this, rootPaneCheckingEnabled,customerToDialog);
			dial.setLocation(300, 100);
			dial.setVisible(true);
			// after dialog is closed:
			if (!customerToEdit.equals(customerToDialog)) { //there has been some change to the customer
				CustomersTableModel model = (CustomersTableModel)jTableCustomers.getModel();
				model.editCustomer(customerToDialog, selectedRow);
			}
		} else {
			JOptionPane.showMessageDialog(this, "No customer is selected!","Customer error", JOptionPane.ERROR_MESSAGE); //TODO localization
		}
	}//GEN-LAST:event_jButtonCustomerEditActionPerformed

	private void jButtonCustomerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerAddActionPerformed
		final AddCustomerDialog dialogAddCustomer = new AddCustomerDialog(this, rootPaneCheckingEnabled);
		final CustomersTableModel model = (CustomersTableModel) jTableCustomers.getModel();
		dialogAddCustomer.setLocation(300, 100);
		dialogAddCustomer.setVisible(true);
		Customer resultCustomer = dialogAddCustomer.getResultCustomer();
		if (resultCustomer != null) {
			model.addCustomer(resultCustomer);
		}
}//GEN-LAST:event_jButtonCustomerAddActionPerformed

	private void jTextFieldFindCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFindCustomerKeyReleased
		String text = jTextFieldFindCustomer.getText();
		TableRowSorter sort = (TableRowSorter) jTableCustomers.getRowSorter();
		if (text.length() == 0) {
			sort.setRowFilter(null);
		} else {
			String[] filter = text.split(" ");
			if (filter.length > 0) {
				String newText = filter[0];
				int length = filter.length;
				for (int i = 1; i < length; i++) {
					newText += "|" + filter[i];
				}
				sort.setRowFilter(RowFilter.regexFilter(newText));
			}
		}
}//GEN-LAST:event_jTextFieldFindCustomerKeyReleased

	private void jTextFieldFindCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFindCustomerMouseClicked
		jTextFieldFindCustomer.setText("");
}//GEN-LAST:event_jTextFieldFindCustomerMouseClicked

	private void jButtonCustomersCzechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomersCzechActionPerformed
		locale = new Locale("cs", "CZ");
		refresh();
	}//GEN-LAST:event_jButtonCustomersCzechActionPerformed

	private void jButtonCustomersSlovakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomersSlovakActionPerformed
		locale = new Locale("sk", "SK");
		refresh();
	}//GEN-LAST:event_jButtonCustomersSlovakActionPerformed

	private void jButtonCustomersEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomersEnglishActionPerformed
		locale = new Locale("en", "US");
		refresh();
	}//GEN-LAST:event_jButtonCustomersEnglishActionPerformed


	public void refresh() {
		//tab names
		jTabbedPane1.setTitleAt(0, java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Customers"));
		jTabbedPane1.setTitleAt(1, java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Cars"));
		jTabbedPane1.setTitleAt(2, java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Orders"));
		

		//Customers tab
		jTableCustomers.getColumnModel().getColumn(1).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Forename"));
		jTableCustomers.getColumnModel().getColumn(2).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Surname"));
		jTableCustomers.getColumnModel().getColumn(3).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Street"));
		jTableCustomers.getColumnModel().getColumn(4).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("HouseNumber"));
		jTableCustomers.getColumnModel().getColumn(5).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Town"));
		jTableCustomers.getColumnModel().getColumn(6).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("State"));
		jTableCustomers.getColumnModel().getColumn(7).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Zipcode"));
		jLabelCustomersFind.setText(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Find"));
		jLabelCustomersLanguage.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Language"));
		jTextFieldFindCustomer.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find a customer"));
		jButtonCustomerAdd.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Add"));
		jButtonCustomerDelete.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Delete"));
		jButtonCustomerEdit.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Edit"));

		//Cars tab
		jTableCars.getColumnModel().getColumn(1).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("CarName").replace(':', ' '));
		jTableCars.getColumnModel().getColumn(2).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Licence plate").replace(':', ' '));
		jTableCars.getColumnModel().getColumn(3).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("CarState").replace(':', ' '));
		jTableCars.getColumnModel().getColumn(4).setHeaderValue(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("CarType").replace(':', ' '));
		jButtonCarAdd.setText(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Add a car"));
		jButtonCarEdit.setText(java.util.ResourceBundle.getBundle("carrental/texts", locale).getString("Edit car"));
		jButton1.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Delete car"));
		jLabel2.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find"));
		jTextField2.setText(java.util.ResourceBundle.getBundle("carrental/texts",locale).getString("Find a car"));
	}

	@Override
	public Locale getLocale() {
		return locale;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new CarRentalFrame().setVisible(true);
			}
		});
	}

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCarAdd;
    private javax.swing.JButton jButtonCarEdit;
    private javax.swing.JButton jButtonCustomerAdd;
    private javax.swing.JButton jButtonCustomerDelete;
    private javax.swing.JButton jButtonCustomerEdit;
    private javax.swing.JButton jButtonCustomerFind;
    private javax.swing.JButton jButtonCustomersCzech;
    private javax.swing.JButton jButtonCustomersEnglish;
    private javax.swing.JButton jButtonCustomersSlovak;
    private javax.swing.JButton jButtonOrderFind;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCustomersFind;
    private javax.swing.JLabel jLabelCustomersLanguage;
    private javax.swing.JLabel jLabelOrdersFind;
    private javax.swing.JPanel jPanelCars;
    private javax.swing.JPanel jPanelCustomers;
    private javax.swing.JPanel jPanelOrders;
    private javax.swing.JPanel jPanelTopMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCars;
    private javax.swing.JTable jTableCustomers;
    private javax.swing.JTable jTableOrders;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldFindCustomer;
    private javax.swing.JTextField jTextFieldOrdersFind;
    // End of variables declaration//GEN-END:variables
	// </editor-fold>
}
